### ISSUE TITLE
NPC Permission Doesn't Work

### ISSUE THREAD

**Issue by LegalSmeagol** [LichtHund/CitizensCMD#39]
The per NPC permission does not work.

We currently use PEX as our permissions system. Guest does NOT have citizenscmd.use.

NPC 181 has permission npc.use and the Guest can still access the right click command of the NPC. 
NPC 181 then has the permission citizenscmd.use and the Guest can still access.

The per NPC permission is not working and there is an immense lack of detail for how the permission works. Poor documentation and effort.

**Comment by I-Knight-I** [comment]
Yeah, the permission to click on the NPC doesn't work.

Like this guy above, regardless of the permissions given, you can always click on the NPC and thus run the command associated with it. What gives?

**Comment by LichtHund** [comment]
The permission command had a small bug that prevented a new permission to be added, it would write the permission to the file but not to memory, but once the server restarted the permission would work as intended.
This has been fixed on b41d8db457fcf50caaa28377723683f9fc19cfab.
The permission citizenscmd.use is only there to give the ability to be negated, should be default to everyone else otherwise.

The permission command was not added to the wiki because a new wiki is being made.

**Comment by LegalSmeagol** [comment]
We have the latest version and can confirm, after extensive testing, that this is not fixed in the latest version.

**Comment by ipsk** [comment]
It is not fixed in any release version, I pointed to the commit that was just now released to fix it.
